import{a as A,S as L,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="47412942-a85f50e46f34315cc96f2bd1d",w="https://pixabay.com/api/";async function m(o,t=1,s=15){const n=`${w}?key=${$}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${s}`;try{return(await A.get(n)).data}catch(e){throw new Error(`Failed to fetch images: ${e.message}`)}}const v=new L(".gallery__item",{captionsData:"alt",captionDelay:250});function f(o,t){const s=o.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:b,comments:F,downloads:E})=>`<a class="gallery__item" href="${e}">
                <div class="gallery__card">
                    <img src="${n}" alt="${r}" loading="lazy" />
                    <div class="gallery__info">
                    <p><b>Likes:</b> ${i}</p>
                    <p><b>Views:</b> ${b}</p>
                    <p><b>Comments:</b> ${F}</p>
                    <p><b>Downloads:</b> ${E}</p>
                    </div>
                </div>
                </a>`).join("");t.insertAdjacentHTML("beforeend",s),v.refresh()}function p(o){const t=document.querySelector(".loader");t.style.display=o?"block":"none"}const _=document.querySelector("#search-form"),c=document.querySelector(".gallery"),g=document.querySelector("#search-input"),a=document.createElement("button");let d=1;const u=15;let h="",y=0;a.textContent="Load more";a.classList.add("load-more");a.style.display="none";document.body.appendChild(a);_.addEventListener("submit",async o=>{o.preventDefault();const t=g.value.trim();if(!t){l.error({title:"Error",message:"Please enter a search query!",backgroundColor:"#EF4040",color:"#FAFAFB",position:"topRight"});return}h=t,d=1,c.innerHTML="",a.style.display="none";try{p(!0);const{hits:s,totalHits:n}=await m(t,d,u);s.length===0?l.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please, try again!",backgroundColor:"#EF4040",color:"#FAFAFB",position:"topRight"}):(y=n,f(s,c),l.success({title:"Success",message:`Found ${y} images!`,position:"topRight",color:"#FAFAFB"}),s.length===u&&(a.style.display="block"))}catch(s){l.error({title:"Error",message:s.message,backgroundColor:"#EF4040",position:"topRight",color:"#FAFAFB"})}finally{p(!1),g.value=""}});a.addEventListener("click",async()=>{d+=1;const o=document.querySelector(".loader");o.style.display="block",a.insertAdjacentElement("beforebegin",o);try{const{hits:t}=await m(h,d,u);f(t,c),S()}catch(t){l.error({title:"Error",message:t.message,backgroundColor:"#EF4040",position:"topRight",color:"#FAFAFB"})}finally{o.style.display="none"}});function S(){const o=c.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
